language: csharp
solution: SLOBSharp.sln
dist: trusty
mono: none
dotnet: 2.1.300
install:
  - dotnet restore
script:
  - dotnet build -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push ./SLOBSharp/bin/Release/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
  on:
    branch: release
notifications:
  email: false