language: csharp
solution: SLOBSharp.sln
dist: trusty
mono: none
dotnet: 2.1.300
install:
  - dotnet restore
script:
  - dotnet build -c Release
  - dotnet test -c Release --no-build SLOBSharp.Tests/SLOBSharp.Tests.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Exclude="[SLOBSharp.Tests*]*"
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f ./SLOBSharp.Tests/coverage.opencover.xml
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push ./SLOBSharp/bin/Release/*.nupkg -k $NUGET_API_KEY
  on:
    branch: release
notifications:
  email: false