language: csharp
solution: SLOBSharp.sln
dist: trusty
mono: none
dotnet: 2.1.300
install:
  - dotnet restore
script:
  - dotnet test SLOBSharp.Tests/SLOBSharp.Tests.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:Exclude="[SLOBSharp.Tests*]*"
  - curl -s https://codecov.io/bash > codecov
  - chmod +x codecov
  - ./codecov -f ./SLOBSharp.Tests/coverage.xml
notifications:
  email: false